[build]
release = true
dist = "release"

[clean]
dist = "release"
cargo = true

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "./tailwindcss -i input.css -o style/output.css", "--minify"]
